default:
  golem_name: nhp.elicitation.tool
  golem_version: 0.0.0.9000
  app_prod: no
  strategies:
    ndg:
      ed-attendances:
        name: ED attendances
        label: "Count"
        min_year: 2013
      inpatient-elective-admissions:
        name: Inpatient elective admissions
        label: "Count"
        min_year: 2013
      inpatient-emergency-admissions:
        name: Inpatient emergency admissions
        label: "Count"
        min_year: 2013
      outpatient-attendances:
        name: Outpatient attendances
        label: "Count"
        min_year: 2013
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
