default:
  golem_name: nhp.elicitation.tool
  golem_version: 0.0.0.9000
  app_prod: no
  range:
    low: -10
    high: 10
  group: "team_a"
  strategies:
    ndg:
      a_outpatient_attendances:
        name: Outpatient attendances (including outpatient procedures) 
        label: "Attendances"
        min_year: 2013
      b_inpatient_elective_admissions:
        name: Elective admissions
        label: "Admissions"
        min_year: 2013
      c_ed_attendances:
        name: A&E attendances (type 1 units only) 
        label: "Attendances"
        min_year: 2013
      d_inpatient_emergency_admissions:
        name: Non-elective admissions
        label: "Admissions"
        min_year: 2013
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
