default:
  golem_name: nhp.elicitation.tool
  golem_version: 0.0.0.9000
  app_prod: no
  horizon: 22
  range:
    low: -7.5
    high: 7.5
  strategies:
    ndg:
      ed_attendances:
        name: ED attendances
        label: "Attendances"
        min_year: 2013
      inpatient_elective_admissions:
        name: Inpatient elective admissions
        label: "Admissions"
        min_year: 2013
      inpatient_emergency_admissions:
        name: Inpatient emergency admissions
        label: "Admissions"
        min_year: 2013
      outpatient_attendances:
        name: Outpatient attendances
        label: "Attendances"
        min_year: 2013
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
